name: Check Licenses

on:
  push:    
    branches:
    - main
    tags:
    - '*'
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  analyze:
    name: Analyze dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup fossa-cli
      uses: camunda/infra-global-github-actions/fossa/setup@a0bc9b0a68c1a9e02aeeb2e061d1292843051269
    - name: Get context info
      id: info
      # uses: ./.github/actions/info
      uses: camunda/infra-global-github-actions/fossa/info@fossa
    - run: |
        echo "::error title=License Check (job=${{ github.job }})::Test ..."
      shell: bash

    # - name: Analyze project
    #   uses: camunda/infra-global-github-actions/fossa/analyze@a0bc9b0a68c1a9e02aeeb2e061d1292843051269
    #   with:
    #     api-key: ${{ secrets.FOSSA_API_KEY }}
    #     branch: ${{  steps.info.outputs.head-ref }}
    #     revision-id: ${{ steps.info.outputs.head-revision }}
    # # PR-only: Check for newly introduced license issues
    # # This step only fails if the PR introduces new license violations.
    # # It does not fail for pre-existing issues already present in the base branch.
    # - name: Check Pull Request for new License Issues
    #   if: steps.info.outputs.is-pull-request == 'true'
    #   # uses: ./.github/actions/pr-check
    #   uses: camunda/infra-global-github-actions/fossa/pr-check@fossa
    #   with:
    #     api-key: ${{ secrets.FOSSA_API_KEY }}
    #     base-ref: ${{ steps.info.outputs.base-ref }}
    #     base-revision: ${{ steps.info.outputs.base-revision }}
    #     revision: ${{ steps.info.outputs.head-revision }}
