name: Merge main to develop
on:
  push:
    branches:
    - main

jobs:
  merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: develop
        fetch-depth: 0
    - name: Merge main to develop and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git merge -m 'chore: merge main to develop' --no-edit origin/main
        git push
